/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Frame;

/**
 *
 * @author Anderson
 */
public class FrameBase extends javax.swing.JFrame {
    /**
     * Creates new form FrameBase
     */
    public FrameBase() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        cadSetor = new javax.swing.JMenuItem();
        cadFuncionario = new javax.swing.JMenuItem();
        OrdServ = new javax.swing.JMenuItem();
        VisuTarefa = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PrefeituraSis - Versão 1.0.0");

        jMenuBar1.setName(""); // NOI18N

        jMenu2.setText("Operações");

        cadSetor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        cadSetor.setText("Cadastrar Setores");
        cadSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSetorActionPerformed(evt);
            }
        });
        jMenu2.add(cadSetor);

        cadFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        cadFuncionario.setText("Cadastrar Funcionário");
        cadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(cadFuncionario);

        OrdServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OrdServ.setText("Ordem de Serviço");
        OrdServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdServActionPerformed(evt);
            }
        });
        jMenu2.add(OrdServ);

        VisuTarefa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        VisuTarefa.setText("Visualizar tarefa");
        VisuTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisuTarefaActionPerformed(evt);
            }
        });
        jMenu2.add(VisuTarefa);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(921, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSetorActionPerformed
        // TODO add your handling code here:
        FrameCadastarSetores fcs = new FrameCadastarSetores();
        fcs.setVisible(true);
    }//GEN-LAST:event_cadSetorActionPerformed

    private void cadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncionarioActionPerformed
        // TODO add your handling code here:
        FrameCadastrarFuncionario fcf = new FrameCadastrarFuncionario();
        fcf.setVisible(true);
    }//GEN-LAST:event_cadFuncionarioActionPerformed

    private void OrdServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdServActionPerformed
        // TODO add your handling code here:
        FrameOrdemServico fos = new FrameOrdemServico();
        fos.setVisible(true);
    }//GEN-LAST:event_OrdServActionPerformed

    private void VisuTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisuTarefaActionPerformed
        // TODO add your handling code here:
        FrameVisualizarTarefa fvt = new FrameVisualizarTarefa();
        fvt.setVisible(true);  
    }//GEN-LAST:event_VisuTarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OrdServ;
    private javax.swing.JMenuItem VisuTarefa;
    private javax.swing.JMenuItem cadFuncionario;
    private javax.swing.JMenuItem cadSetor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
